#!/bin/bash
set -e

VTREE_VERSION="${VTREE_VERSION:-v1.1}"
SDL2_HEADERS_VERSION="${SDL2_HEADERS_VERSION:-release-2.30.10}"
OUTPUT_DIR="${OUTPUT_DIR:-/output}"

# aemiii91/miyoomini-toolchain ships SDL **1.2** only — vTree needs SDL2.
# We vendor SDL2 headers from upstream and link against spruce's SDL2 libs.
TOOLCHAIN=/opt/miyoomini-toolchain
CROSS=arm-linux-gnueabihf
export PATH="$TOOLCHAIN/usr/bin:$PATH"
export CC="${CROSS}-gcc"
export STRIP="${CROSS}-strip"

SPRUCE_LIBS=/opt/spruce-mini-libs

CFLAGS_COMMON="-O2 -mcpu=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard -fomit-frame-pointer -ffunction-sections -fdata-sections"
LDFLAGS_COMMON="-Wl,--gc-sections -Wl,--allow-shlib-undefined"

# ============================================================
# Vendor SDL2 + SDL2_ttf + SDL2_image headers (the aemiii91 toolchain
# is SDL 1.2-only). Headers are arch-independent — runtime ABI comes
# from the spruce SDL2 libs at $SPRUCE_LIBS.
# ============================================================
PREFIX=/build/local
mkdir -p "$PREFIX/include/SDL2"

echo "=== Vendoring SDL2 headers ${SDL2_HEADERS_VERSION} ==="
git clone --depth 1 --branch "$SDL2_HEADERS_VERSION" \
    https://github.com/libsdl-org/SDL.git /tmp/SDL_src
cp /tmp/SDL_src/include/*.h "$PREFIX/include/SDL2/"
# SDL_config.h is normally generated by configure/cmake; fall back to the
# minimal stub which works for header consumers.
cp /tmp/SDL_src/include/SDL_config_minimal.h "$PREFIX/include/SDL2/SDL_config.h"

echo "=== Vendoring SDL2_ttf headers ==="
git clone --depth 1 --branch release-2.22.0 \
    https://github.com/libsdl-org/SDL_ttf.git /tmp/SDL_ttf_src
cp /tmp/SDL_ttf_src/SDL_ttf.h "$PREFIX/include/SDL2/"

echo "=== Vendoring SDL2_image headers ==="
git clone --depth 1 --branch release-2.8.2 \
    https://github.com/libsdl-org/SDL_image.git /tmp/SDL_image_src
cp /tmp/SDL_image_src/include/SDL_image.h "$PREFIX/include/SDL2/" 2>/dev/null || \
    cp /tmp/SDL_image_src/SDL_image.h     "$PREFIX/include/SDL2/"

echo "=== Building vTree ${VTREE_VERSION} for Miyoo Mini (armhf) ==="

git clone https://github.com/MustardOS/vtree.git
cd vtree
git checkout "$VTREE_VERSION"

for dir in /patches/common /patches/miyoomini; do
    [ -d "$dir" ] || continue
    for patch in "$dir"/*.patch; do
        [ -f "$patch" ] && echo "Applying: $(basename "$patch")" && git apply "$patch"
    done
    for pypatch in "$dir"/*.py; do
        [ -f "$pypatch" ] && echo "Applying: $(basename "$pypatch")" && python3 "$pypatch"
    done
done

# SDL_clamp compat shim (harmless on SDL >= 2.24)
cat > sdl_compat.h <<'EOF'
#include <stdio.h>
#ifndef SDL_clamp
#define SDL_clamp(x, a, b) (((x) < (a)) ? (a) : (((x) > (b)) ? (b) : (x)))
#endif
EOF

SDL_CFLAGS="-I$PREFIX/include -I$PREFIX/include/SDL2 -D_REENTRANT -include ./sdl_compat.h"
# Link against spruce's custom SDL2 stack; DT_NEEDED will record libSDL2-2.0.so.0
SDL_LIBS="-L$SPRUCE_LIBS -Wl,-rpath-link,$SPRUCE_LIBS -lSDL2_ttf -lSDL2_image -lSDL2 -lm"

make release CC=${CROSS}-gcc \
    SDL2_CFLAGS="$SDL_CFLAGS" \
    SDL2_LIBS="$SDL_LIBS" \
    CFLAGS_REL="-Wall -Wextra -std=c99 $SDL_CFLAGS -DSDL_MAIN_HANDLED -D_POSIX_C_SOURCE=200809L -O2 -DNDEBUG $CFLAGS_COMMON" \
    LDFLAGS_REL="$LDFLAGS_COMMON"

${STRIP} -s vtree

# ============================================================
# Collect output — binary + runtime assets only
# (spruce already ships SDL2 stack in miyoo/lib/, no need to bundle)
# ============================================================
echo "=== Collecting output ==="
mkdir -p "$OUTPUT_DIR"
cp vtree "$OUTPUT_DIR/"
[ -d res ]                      && cp -r res "$OUTPUT_DIR/"
[ -d fonts ]                    && cp -r fonts "$OUTPUT_DIR/"
[ -d glyph ]                    && cp -r glyph "$OUTPUT_DIR/"
[ -d lang ]                     && cp -r lang "$OUTPUT_DIR/"
[ -f config.ini ]               && cp config.ini "$OUTPUT_DIR/"
[ -d theme ]                    && cp -r theme "$OUTPUT_DIR/"
[ -f mux_lang.ini ]             && cp mux_lang.ini "$OUTPUT_DIR/"
[ -f gamecontrollerdb.txt ]     && cp gamecontrollerdb.txt "$OUTPUT_DIR/"
[ -f LICENSE ]                  && cp LICENSE "$OUTPUT_DIR/"
[ -f README.md ]                && cp README.md "$OUTPUT_DIR/"

echo "=== DT_NEEDED entries ==="
${CROSS}-readelf -d "$OUTPUT_DIR/vtree" | grep NEEDED || true

echo "=== Build complete ==="
ls -la "$OUTPUT_DIR/"
