name: Build All

on:
  workflow_dispatch:
    inputs:
      vtree_version:
        description: 'vTree version/tag/commit'
        default: 'master'
      spruce_ref:
        description: 'spruceOS ref to pull Mini SDL2 libs from'
        default: 'main'

permissions:
  contents: write

jobs:
  universal:
    uses: ./.github/workflows/build-universal.yml
    with:
      vtree_version: ${{ inputs.vtree_version }}

  a30:
    uses: ./.github/workflows/build-a30.yml
    with:
      vtree_version: ${{ inputs.vtree_version }}

  miyoomini:
    uses: ./.github/workflows/build-miyoomini.yml
    with:
      vtree_version: ${{ inputs.vtree_version }}
      spruce_ref: ${{ inputs.spruce_ref }}
